### ISSUE TITLE
Milestone 2 Tasks 

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/Mental-Health-Analysis_Vis-App#11]
The following is the tasks needed to be done this week:

# General
- [x] Develop your shiny app on a **public github.com** repository 
- [x] Deploy your Shiny app to **shinyapps.io**. Sometimes deployment will introduce bugs, so make sure to save some time for debugging! The shinyapps.io console logs are very helpful here.
- [x] Tag a release of your Shiny app, and submit a link to that in your private repository for this milestone. 
- [x] code of conduct
- [x] In addition to your Shiny app submission, you must document the functionality of your Shiny app in a markdown document in your public repo for this milestone. YOU MUST INCLUDE **SCREENSHOTS** illustrating all of the functions your Shiny app performs. If your Shiny app fails to deploy to shinyapps.io, we will be grading you solely on your screenshots.
- [x] Ensure that your markdown submission as a whole is easy to read: use appropriate formatting that clearly distinguishes between our questions and your answer, between different sub-parts of your answer, and with visible differences between code and English.
- [x] Ensure your submitted private repo is organized. It should be easy to find files and links.

**Comment by chaomander2018** [comment]
- [ ] A reminder for us to adjust the sidebar panel width
